In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [37]:
a=np.array([[1,2],[3,4]])

In [38]:
a

array([[1, 2],
       [3, 4]])

In [40]:
a=np.array([[1,2,3],[4,5,6],[2,5,7],[2,6,4]])

In [41]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [2, 5, 7],
       [2, 6, 4]])

In [11]:
a.shape()

TypeError: 'tuple' object is not callable

In [12]:
a.shape

(3, 3)

In [14]:
a.shape

(3, 3)

In [20]:
a.shape

(4, 3)

In [21]:
a.reshape(2,6)

array([[1, 2, 3, 4, 5, 6],
       [2, 5, 7, 2, 6, 4]])

In [22]:
a.reshape(3,4)

array([[1, 2, 3, 4],
       [5, 6, 2, 5],
       [7, 2, 6, 4]])

In [23]:
a.reshape(2,7)

ValueError: cannot reshape array of size 12 into shape (2,7)

In [24]:
a.reshape(2,5)

ValueError: cannot reshape array of size 12 into shape (2,5)

In [25]:
a.min()

1

In [26]:
a.max()

7

In [27]:
a.dtype()

TypeError: 'numpy.dtype[int32]' object is not callable

In [28]:
a.dtype

dtype('int32')

In [29]:
a.size

12

In [42]:
a.itemsize

4

In [31]:
a.data

In [32]:
print(a)

[[1 2 3]
 [4 5 6]
 [2 5 7]
 [2 6 4]]


In [47]:
b=np.array([[1,2,3],[4,5,6],[6,7,8],[2,6,3]],dtype="float64")

In [48]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [6., 7., 8.],
       [2., 6., 3.]])

In [49]:
b.itemsize

8

In [53]:
b.reshape(4,3)

array([[1., 2., 3.],
       [4., 5., 6.],
       [6., 7., 8.],
       [2., 6., 3.]])

In [54]:
b.ndim

2

In [55]:
y=np.array(5)

In [56]:
y

array(5)

In [57]:
t=np.arange(5)

In [58]:
t

array([0, 1, 2, 3, 4])

In [59]:
t=np.arange(15).reshape(3,5)

In [60]:
t

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
t=np.arange(15)

In [62]:
t

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
print(t)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [64]:
a=t.reshape(3,5)

In [65]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
a=t.reashape(5,3)

AttributeError: 'numpy.ndarray' object has no attribute 'reashape'

In [67]:
a=t.reshape(5,3)

In [68]:
t

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [69]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [72]:
ra=np.array([[23,34,55],[45,67,89]])

In [73]:
ra

array([[23, 34, 55],
       [45, 67, 89]])

In [74]:
print(ra.ravel())

[23 34 55 45 67 89]


In [75]:
print(a.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [76]:
a=np.array([5,9,13])

In [77]:
a

array([ 5,  9, 13])

In [78]:
type(a)

numpy.ndarray

In [89]:
m=np.array(np.mat('1 2 3 3 4 5'))

In [90]:
m

array([[1, 2, 3, 3, 4, 5]])

In [91]:
a=[1,2,3,4]

In [92]:
c=np.array(a)

In [93]:
c

array([1, 2, 3, 4])

In [96]:
type(a)

list

In [97]:
b=np.asarray(c)

In [98]:
b

array([1, 2, 3, 4])

In [99]:
c

array([1, 2, 3, 4])

In [101]:
b==c

array([ True,  True,  True,  True])

In [102]:
b>c

array([False, False, False, False])

In [106]:
my_mat=[[1,2,3],[3,4,5],[5,6,7]]

In [107]:
mat=np.array(my_mat)

In [108]:
print(mat)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [109]:
print(type(mat))

<class 'numpy.ndarray'>


In [110]:
print(mat.shape)

(3, 3)


In [112]:
print(mat.size)

9


In [114]:
print(mat.ndim)

2


In [115]:
print(mat.dtype)

int32


In [116]:
print(list(range(2,10.4,.4)))

TypeError: 'float' object cannot be interpreted as an integer

In [117]:
a=np.array(2,10.5,.4)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [118]:
a=np.arange(2,10.5,.4)

In [119]:
a

array([ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,  4.8,  5.2,  5.6,  6. ,
        6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,  9.2,  9.6, 10. , 10.4])

In [120]:
a[::-1]

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,
        6. ,  5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ])

In [121]:
a=np.arange(50,0,-5)

In [122]:
a

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5])

In [123]:
a[;:-1]

SyntaxError: invalid syntax (Temp/ipykernel_14312/1125775482.py, line 1)

In [124]:
a[::-1]

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [129]:
l=np.linspace(10,100,10)

In [130]:
l

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [132]:
l=np.linspace(10,20,20)

In [133]:
l

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [135]:
np.linspace(2.0,3.0,num=4,endpoint=True,retstep=True)

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)

In [136]:
np.linspace(2.0,3.0,num=4,endpoint=False,retstep=False)

array([2.  , 2.25, 2.5 , 2.75])

In [139]:
print(np.zeros((5,6)))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [140]:
print(np.ones((4,7)))

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [142]:
print(5*np.ones((4,6)))

[[5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]]


In [143]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [149]:
a=np.random.randint(1,40,50)

In [150]:
a

array([ 6, 34, 35, 18, 28, 15,  5, 22, 16,  7, 23, 14, 16, 36,  7, 13, 11,
        2, 19, 17, 13, 36, 18, 15, 36, 35, 11,  1, 14,  5, 37, 18, 31,  7,
       12, 14, 17, 32, 27, 14,  1,  4, 25, 18, 17, 18, 17, 32, 20,  2])

In [153]:
b=np.clip(a,a_min=10,a_max=30)

In [155]:
print(np.where(b<10))

(array([], dtype=int64),)


In [156]:
print(np.where(a==30))

(array([], dtype=int64),)


In [157]:
print(np.where(b==30))

(array([ 1,  2, 13, 21, 24, 25, 30, 32, 37, 47], dtype=int64),)


In [160]:
import numpy as np
from numpy.random import randint as ri

In [161]:
a=ri(1,99,40)

In [162]:
a

array([14, 32, 64, 34, 57, 85,  4, 26, 56, 88, 30, 96, 49,  8, 72, 89, 60,
       21, 95, 55, 37, 33, 18, 47, 95, 23, 84, 79, 15, 90, 14, 71, 96, 28,
       30, 73, 68, 42, 65, 25])

In [164]:
b=a.reshape(2,2,10)

In [165]:
b

array([[[14, 32, 64, 34, 57, 85,  4, 26, 56, 88],
        [30, 96, 49,  8, 72, 89, 60, 21, 95, 55]],

       [[37, 33, 18, 47, 95, 23, 84, 79, 15, 90],
        [14, 71, 96, 28, 30, 73, 68, 42, 65, 25]]])

In [166]:
m=ri(1,100,25).reshape(5,5)

In [167]:
m

array([[67, 19, 85, 58, 34],
       [29, 41, 16, 93, 12],
       [23, 66, 64, 73, 37],
       [64, 49, 85, 20, 19],
       [76, 88, 42, 20, 91]])

In [168]:
print(np.sort(m))

[[19 34 58 67 85]
 [12 16 29 41 93]
 [23 37 64 66 73]
 [19 20 49 64 85]
 [20 42 76 88 91]]


In [170]:
print(np.sort(m,axis=0))

[[23 19 16 20 12]
 [29 41 42 20 19]
 [64 49 64 58 34]
 [67 66 85 73 37]
 [76 88 85 93 91]]


In [171]:
mat=np.arange(1,10,1).reshape(3,3)

In [172]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [173]:
mat[7]

IndexError: index 7 is out of bounds for axis 0 with size 3

In [174]:
mat[2][2]

9

In [175]:
print(" ",mat[0:2,[1,2]])

  [[2 3]
 [5 6]]


In [176]:
print(" ",mat[0:2,1:3])

  [[2 3]
 [5 6]]


In [178]:
mat[1][2]=56

In [180]:
mat

array([[ 1,  2,  3],
       [ 4,  5, 56],
       [ 7,  8,  9]])

In [181]:
mat=np.array(ri(10,100,15)).reshape(3,5)

In [182]:
mat

array([[23, 43, 37, 87, 28],
       [97, 92, 74, 69, 15],
       [33, 29, 77, 81, 77]])

In [183]:
xyz=mat[mat>70]

In [184]:
xyz

array([87, 97, 92, 74, 77, 81, 77])

In [185]:
mat>50

array([[False, False, False,  True, False],
       [ True,  True,  True,  True, False],
       [False, False,  True,  True,  True]])

In [186]:
print(np.where(mat==55))

(array([], dtype=int64), array([], dtype=int64))


In [188]:
mat1=np.array(ri(10,100,20)).reshape(4,5)

In [195]:
mat2=np.array(ri(10,100,20)).reshape(4,5)

In [196]:
mat1

array([[50, 72, 72, 91, 22],
       [43, 86, 35, 96, 76],
       [15, 10, 18, 95, 86],
       [69, 57, 48, 17, 82]])

In [197]:
mat2

array([[30, 70, 64, 82, 55],
       [59, 20, 36, 93, 82],
       [14, 70, 80, 78, 15],
       [53, 28, 92, 89, 72]])

In [198]:
y=mat1+mat2

In [199]:
y

array([[ 80, 142, 136, 173,  77],
       [102, 106,  71, 189, 158],
       [ 29,  80,  98, 173, 101],
       [122,  85, 140, 106, 154]])

In [200]:
mat1*mat2

array([[1500, 5040, 4608, 7462, 1210],
       [2537, 1720, 1260, 8928, 6232],
       [ 210,  700, 1440, 7410, 1290],
       [3657, 1596, 4416, 1513, 5904]])

In [201]:
mat1/mat2

array([[1.66666667, 1.02857143, 1.125     , 1.1097561 , 0.4       ],
       [0.72881356, 4.3       , 0.97222222, 1.03225806, 0.92682927],
       [1.07142857, 0.14285714, 0.225     , 1.21794872, 5.73333333],
       [1.30188679, 2.03571429, 0.52173913, 0.19101124, 1.13888889]])

In [202]:
mat1-2*mat2

array([[ -10,  -68,  -56,  -73,  -88],
       [ -75,   46,  -37,  -90,  -88],
       [ -13, -130, -142,  -61,   56],
       [ -37,    1, -136, -161,  -62]])

In [203]:
5*mat1-4*mat2

array([[ 130,   80,  104,  127, -110],
       [ -21,  350,   31,  108,   52],
       [  19, -230, -230,  163,  370],
       [ 133,  173, -128, -271,  122]])

In [205]:
start=np.ones((3,3))

In [206]:
start

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [212]:
add_rows=np.array([1,0,2])

In [213]:
y=start+add_rows

In [214]:
y

array([[2., 1., 3.],
       [2., 1., 3.],
       [2., 1., 3.]])

In [220]:
new_rows=add_rows.T

In [221]:
new_rows

array([1, 0, 2])

In [222]:
test=new_rows+start

In [223]:
test

array([[2., 1., 3.],
       [2., 1., 3.],
       [2., 1., 3.]])

In [225]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp